### ISSUE TITLE
Preview doesn't display

### ISSUE THREAD

**Issue by patrikhermansson** [tomw/TWCameraView#3]
I have some issues implementing the camera preview. Get everything to compile but no preview is displayed. Is it possible to include a small use example?

**Comment by tomw** [comment]
Have you followed that's in the 'Usage' section of the readme? You'll need to call `startPreview`.

**Comment by patrikhermansson** [comment]
Yes I have. Followed it in detail. But now getting the error when I call `startPreview`.

`*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** -[AVCaptureFigVideoDevice setFocusPointOfInterest:] May not be called without first successfully gaining exclusive ownership of the device using -lockForConfiguration:'`

I add `TWCameraViewDelegate` to my ViewController, include `func didReceiveMemoryWarning` as well as `func cameraViewDidCaptureImage` and call `cameraView.startPreview` in `viewDidLoad()`

**Comment by tomw** [comment]
Ah, I see. I've tagged a new release. Can you update to version 1.1.1 and let me know if that solves it?

**Comment by patrikhermansson** [comment]
Thanks for the effort! It does solve the lock problem but preview doesn't start still, just left bland and this printed in terminal:

`2017-02-02 09:34:22.846051 ***[418:82620] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-02-02 09:34:22.854757 ***[418:82620] [MC] Reading from public effective user settings.`

**Comment by tomw** [comment]
Have you added `Privacy - Camera Usage Description` to your Info.plist as the readme suggests?

**Comment by patrikhermansson** [comment]
yes, error for that is different

**Comment by tomw** [comment]
& your view has it's frame set correctly?

**Comment by patrikhermansson** [comment]
I'm not sure. I use a plain view and connect it to the controller in ui builder

**Comment by tomw** [comment]
Can you post some code snippets? Unfortunately it's hard to help you st this point, I think it might be a layout problem

**Comment by patrikhermansson** [comment]
You're probably right that it's a layout problem. I understand it's difficult to help here. This is the code from my view controller:

```
import UIKit
import TWCameraView
class ReportCameraViewController: UIViewController, TWCameraViewDelegate {

override func viewDidLoad() {
        super.viewDidLoad()

        let cameraView = TWCameraView()
        cameraView.delegate = self
        self.view.addSubview(cameraView)
        cameraView.startPreview(requestPermissionIfNeeded: true)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
        // Do any additional setup after loading the view.
    }
    
    func cameraViewDidCaptureImage(image: UIImage, cameraView: TWCameraView) {
        
        
    }
    
    func cameraViewDidFailToCaptureImage(error: Error, cameraView: TWCameraView) {
        
    }
}
```

Then connect that to my view in the ui builder, assigning a class to my view:

<img width="676" alt="screen shot 2017-02-02 at 10 23 09" src="https://cloud.githubusercontent.com/assets/9743520/22545708/b145650a-e931-11e6-9ab7-e004de1a68f0.png">

**Comment by tomw** [comment]
Can you try adding:

```
cameraView.frame = self.view.bounds
cameraView.autoresizingMask = [ .flexibleHeight, .flexibleWidth ]
```

**Comment by patrikhermansson** [comment]
That solved it! Thanks so much for the help

**Comment by tomw** [comment]
No problem!
